#ifndef __IBASE_H__
#define __IBASE_H__
#include "icommon.h"

__NAMESPACE_GUARD_BEGIN(StreamOverlay)
__NAMESPACE_GUARD_BEGIN(Interfaces)
__EXTERN_C_GUARD_BEGIN

DECLARE_INTERFACE IBase
{
    DECLARE_INTERFACE_VFTABLE
    DECLARE_INTERFACE_VFUNCTION(TryCastTo, bool)() PURE;
    DECLARE_INTERFACE_VFUNCTION(Reference, bool)(IThis_ void** ppInterface) PURE;
    DECLARE_INTERFACE_VFUNCTION(Release, bool)() PURE;
    DELCARE_INTERFACE_VFTABLE_END
};

__EXTERN_C_GUARD_END
__NAMESPACE_GUARD_END
__NAMESPACE_GUARD_END
#endif//__IBASE_H__ GUARD