#include "interfaces/IBase.h"

__EXTERN_C_GUARD_BEGIN
__NAMESPACE_GUARD_BEGIN(ZDC)
__NAMESPACE_GUARD_BEGIN(StreamOverlay)
__NAMESPACE_GUARD_BEGIN(Interfaces)

DEFINE_INTERFACE_UUID(IBase, RegisterInterface("IBase"));

__NAMESPACE_GUARD_END
__NAMESPACE_GUARD_END
__NAMESPACE_GUARD_END
__EXTERN_C_GUARD_END